#!/usr/bin/env python3
"""Snapshot the live game as an immutable /samegreattaste/vNN archive.

  python3 tools/release.py                      # snapshot the current build as the next vNN
  python3 tools/release.py --note "Adds act 4"  # ...with a note for the listing
  python3 tools/release.py --id v00 --from ~/old.html --note "No sound, no transitions."

Snapshots are byte-identical copies, never rewritten, so an archived build
always behaves exactly as it did on the day it shipped. Both commands also
regenerate samegreattaste/versions/index.html from versions.tsv.
"""
import argparse, datetime, html, re, shutil, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GAME = ROOT / "samegreattaste"
LIVE = GAME / "index.html"
MANIFEST = GAME / "versions.tsv"


def read_manifest():
    rows = []
    if MANIFEST.exists():
        for line in MANIFEST.read_text().splitlines():
            if not line.strip() or line.startswith("#"):
                continue
            parts = (line.split("\t") + ["", ""])[:3]
            rows.append({"id": parts[0].strip(), "date": parts[1].strip(),
                         "note": parts[2].strip()})
    return rows


def write_manifest(rows):
    rows.sort(key=lambda r: r["id"])
    out = ["# id\tdate\tnote",
           "# Newest last. Edit notes freely; tools/release.py rebuilds the listing from this."]
    out += [f"{r['id']}\t{r['date']}\t{r['note']}" for r in rows]
    MANIFEST.write_text("\n".join(out) + "\n")


def next_id(rows):
    nums = [int(m.group(1)) for r in rows if (m := re.fullmatch(r"v(\d+)", r["id"]))]
    return f"v{(max(nums) + 1) if nums else 1:02d}"


def render_listing(rows):
    newest = rows[-1]["id"] if rows else None
    items = []
    for r in reversed(rows):
        note = html.escape(r["note"]) or "&nbsp;"
        tag = ' <span class="tag">current</span>' if r["id"] == newest else ""
        items.append(
            f'    <li>\n'
            f'      <a href="/samegreattaste/{r["id"]}">{r["id"]}{tag}</a>\n'
            f'      <p>{note}</p>\n'
            f'      <time datetime="{html.escape(r["date"])}">{html.escape(r["date"])}</time>\n'
            f'    </li>'
        )
    return f"""<!doctype html>
<!-- Generated by tools/release.py from samegreattaste/versions.tsv. Do not edit by hand. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Same Great Taste — versions</title>
<link rel="icon" href="/logo.svg" type="image/svg+xml">
<meta name="robots" content="noindex">
<meta name="theme-color" content="#f5eddd">
<style>
  /* Act 1 palette, shared with the landing page and the game itself. */
  :root{{
    --bg:#f5eddd; --card:#fffaf0; --ink:#3b2f24; --ink2:#7a6a56;
    --line:#e4d6bd; --accent:#a54f22; --accent-ink:#fff6ec;
  }}
  *{{box-sizing:border-box;margin:0;padding:0}}
  body{{
    background:var(--bg); color:var(--ink); min-height:100vh; padding:12vmin 6vmin;
    font:400 1rem/1.6 Georgia,'Iowan Old Style','Times New Roman',serif;
    display:flex; justify-content:center;
  }}
  main{{width:100%;max-width:34rem}}
  .mark{{width:60px;height:60px;display:block;margin-bottom:2rem}}
  h1{{font-size:1.4rem;font-weight:400;letter-spacing:-.01em}}
  .lede{{color:var(--ink2);font-size:.95rem;margin:.5rem 0 2.5rem}}
  .lede a{{color:var(--accent)}}
  ul{{list-style:none}}
  li{{padding:1.15rem 0;border-top:1px solid var(--line)}}
  li a{{color:var(--ink);text-decoration:none;font-size:1.05rem}}
  li a:hover{{color:var(--accent)}}
  .tag{{
    font-family:ui-sans-serif,system-ui,-apple-system,sans-serif;
    font-size:.6rem;font-weight:600;letter-spacing:.1em;text-transform:uppercase;
    color:var(--accent-ink); background:var(--accent); padding:.2rem .45rem;
    border-radius:4px; vertical-align:.15em; margin-left:.5rem;
  }}
  li p{{color:var(--ink2);font-size:.92rem;margin-top:.2rem}}
  time{{color:var(--ink2);font-size:.78rem;opacity:.8}}
  .back{{display:inline-block;margin-top:2.5rem;color:var(--ink2);font-size:.9rem}}
  .back:hover{{color:var(--accent)}}
</style>
</head>
<body>
  <main>
    <img class="mark" src="/logo.svg" alt="">
    <h1>Same Great Taste — versions</h1>
    <p class="lede">Every build that has shipped, kept playable at its own address.
      <a href="/samegreattaste">/samegreattaste</a> always serves the current one.</p>
    <ul>
{chr(10).join(items)}
    </ul>
    <a class="back" href="/samegreattaste">&larr; Play the current build</a>
  </main>
</body>
</html>
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--id", help="version id to write, e.g. v00 (default: next unused)")
    ap.add_argument("--from", dest="src", help="source HTML (default: the live build)")
    ap.add_argument("--note", default="", help="one-line description for the listing")
    ap.add_argument("--relist", action="store_true",
                    help="only regenerate the listing; take no snapshot")
    a = ap.parse_args()

    rows = read_manifest()

    if not a.relist:
        src = Path(a.src).expanduser() if a.src else LIVE
        if not src.is_file():
            sys.exit(f"no such file: {src}")

        vid = a.id or next_id(rows)
        if not re.fullmatch(r"v\d+", vid):
            sys.exit(f"version id must look like v01, got {vid!r}")

        dest = GAME / vid / "index.html"
        if dest.exists():
            sys.exit(f"{vid} already exists — archives are immutable, pick another id")

        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(src, dest)

        rows = [r for r in rows if r["id"] != vid]
        rows.append({"id": vid, "date": datetime.date.today().isoformat(), "note": a.note})
        write_manifest(rows)
        print(f"archived {src} -> /samegreattaste/{vid}")

    (GAME / "versions").mkdir(parents=True, exist_ok=True)
    (GAME / "versions" / "index.html").write_text(render_listing(read_manifest()))
    print("rebuilt /samegreattaste/versions")


if __name__ == "__main__":
    main()
