#!/usr/bin/env python3
"""Snapshot a build of the game as an immutable /samegreattaste/vN archive.

  python3 tools/release.py --id v5 --status beta --note "..."   # freeze the live build
  python3 tools/release.py --id v2 --from ~/old.html --note "No sound, no transitions."
  python3 tools/release.py --relist                             # rebuild the listing only

Version ids track the game's own save format — a build whose CFG.saveKey is
'sgt_save_v4' is archived as v4 — so two archives can never read each other's
saved state.

Snapshots are byte-identical copies and are not edited afterwards, so an
archived build behaves exactly as it did the day it shipped.

Whichever archive matches samegreattaste/index.html byte for byte is the one
being served at /samegreattaste; the listing works that out rather than
assuming it is the newest.
"""
import argparse, datetime, html, re, shutil, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GAME = ROOT / "samegreattaste"
LIVE = GAME / "index.html"
MANIFEST = GAME / "versions.tsv"

HEADER = [
    "# id\tdate\tstatus\tnote",
    "# Version ids track the game's own save format (CFG.saveKey: sgt_save_v3 -> v3).",
    "# status is the badge shown in the listing: playable, beta, archive, or blank.",
    "# Newest last. tools/release.py rebuilds the listing from this file.",
]


def version_sort_key(vid):
    m = re.fullmatch(r"v(\d+)", vid)
    return (0, int(m.group(1))) if m else (1, 0)


def read_manifest():
    rows = []
    if MANIFEST.exists():
        for line in MANIFEST.read_text().splitlines():
            if not line.strip() or line.startswith("#"):
                continue
            f = (line.split("\t") + ["", "", ""])[:4]
            rows.append({"id": f[0].strip(), "date": f[1].strip(),
                         "status": f[2].strip(), "note": f[3].strip()})
    return rows


def write_manifest(rows):
    rows.sort(key=lambda r: version_sort_key(r["id"]))
    body = [f"{r['id']}\t{r['date']}\t{r['status']}\t{r['note']}" for r in rows]
    MANIFEST.write_text("\n".join(HEADER + body) + "\n")


def next_id(rows):
    nums = [int(m.group(1)) for r in rows if (m := re.fullmatch(r"v(\d+)", r["id"]))]
    return f"v{(max(nums) + 1) if nums else 1}"


def live_id(rows):
    """Which archive is currently served at /samegreattaste, by content."""
    if not LIVE.is_file():
        return None
    live = LIVE.read_bytes()
    for r in rows:
        f = GAME / r["id"] / "index.html"
        if f.is_file() and f.read_bytes() == live:
            return r["id"]
    return None


def render_listing(rows):
    served = live_id(rows)
    items = []
    for r in sorted(rows, key=lambda r: version_sort_key(r["id"]), reverse=True):
        badges = ""
        if r["status"]:
            cls = "badge " + (r["status"] if r["status"] in ("playable", "beta", "archive") else "")
            badges += f'<span class="{cls.strip()}">{html.escape(r["status"])}</span>'
        here = ' <span class="served">served at /samegreattaste</span>' if r["id"] == served else ""
        items.append(
            f'    <li>\n'
            f'      <p class="row"><a href="/samegreattaste/{r["id"]}">{r["id"]}</a>{badges}</p>\n'
            f'      <p class="note">{html.escape(r["note"]) or "&nbsp;"}</p>\n'
            f'      <p class="meta"><time datetime="{html.escape(r["date"])}">'
            f'{html.escape(r["date"])}</time>{here}</p>\n'
            f'    </li>'
        )

    lede = ("Every build that has shipped, kept playable at its own address. "
            "<a href=\"/samegreattaste\">/samegreattaste</a> serves the build marked playable "
            "— which is not always the newest one.")

    return f"""<!doctype html>
<!-- Generated by tools/release.py from samegreattaste/versions.tsv. Do not edit by hand. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Same Great Taste — versions</title>
<link rel="icon" href="/favicon.ico" sizes="32x32">
<link rel="icon" href="/logo.svg?v=2" type="image/svg+xml">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<link rel="manifest" href="/site.webmanifest">
<meta name="apple-mobile-web-app-title" content="Same Great Taste">
<meta name="robots" content="noindex">
<meta name="theme-color" content="#f5eddd">
<style>
  /* Act 1 palette, shared with the landing page and the game itself. */
  :root{{
    --bg:#f5eddd; --ink:#3b2f24; --ink2:#7a6a56;
    --line:#e4d6bd; --accent:#a54f22; --accent-ink:#fff6ec;
  }}
  *{{box-sizing:border-box;margin:0;padding:0}}
  body{{
    background:var(--bg); color:var(--ink); min-height:100vh; padding:12vmin 6vmin;
    font:400 1rem/1.6 Georgia,'Iowan Old Style','Times New Roman',serif;
    display:flex; justify-content:center;
  }}
  main{{width:100%;max-width:34rem}}
  .mark{{width:60px;height:60px;display:block;margin-bottom:2rem}}
  h1{{font-size:1.4rem;font-weight:400;letter-spacing:-.01em}}
  .lede{{color:var(--ink2);font-size:.95rem;margin:.5rem 0 2.5rem}}
  .lede a{{color:var(--accent)}}
  ul{{list-style:none}}
  li{{padding:1.15rem 0;border-top:1px solid var(--line)}}
  .row{{display:flex;align-items:center;flex-wrap:wrap;gap:.5rem}}
  .row a{{color:var(--ink);text-decoration:none;font-size:1.05rem}}
  .row a:hover{{color:var(--accent)}}
  .badge{{
    font-family:ui-sans-serif,system-ui,-apple-system,sans-serif;
    font-size:.6rem;font-weight:600;letter-spacing:.1em;text-transform:uppercase;
    padding:.2rem .45rem;border-radius:4px;
    color:var(--ink2); border:1px solid var(--line);
  }}
  .badge.playable{{color:var(--accent-ink);background:var(--accent);border-color:var(--accent)}}
  .badge.beta{{color:var(--ink2);background:transparent;border-style:dashed}}
  .badge.archive{{color:var(--ink2);background:transparent;opacity:.65}}
  .note{{color:var(--ink2);font-size:.92rem;margin-top:.3rem}}
  .meta{{margin-top:.35rem;font-size:.78rem;color:var(--ink2);opacity:.8}}
  .served{{
    font-family:ui-sans-serif,system-ui,-apple-system,sans-serif;
    font-size:.7rem;
  }}
  .served::before{{content:" · "}}
  .back{{display:inline-block;margin-top:2.5rem;color:var(--ink2);font-size:.9rem}}
  .back:hover{{color:var(--accent)}}
</style>
</head>
<body>
  <main>
    <a href="/"><img class="mark" src="/logo.svg?v=2" alt="Goosen Games"></a>
    <h1>Same Great Taste — versions</h1>
    <p class="lede">{lede}</p>
    <ul>
{chr(10).join(items)}
    </ul>
    <a class="back" href="/samegreattaste">&larr; Play</a>
  </main>
</body>
</html>
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--id", help="version id, e.g. v5 (default: next unused)")
    ap.add_argument("--from", dest="src", help="source HTML (default: the live build)")
    ap.add_argument("--note", default="", help="one-line description for the listing")
    ap.add_argument("--status", default="", help="badge: playable, beta, or blank")
    ap.add_argument("--relist", action="store_true",
                    help="only regenerate the listing; take no snapshot")
    a = ap.parse_args()

    rows = read_manifest()

    if not a.relist:
        src = Path(a.src).expanduser() if a.src else LIVE
        if not src.is_file():
            sys.exit(f"no such file: {src}")

        vid = a.id or next_id(rows)
        if not re.fullmatch(r"v\d+", vid):
            sys.exit(f"version id must look like v4, got {vid!r}")

        dest = GAME / vid / "index.html"
        if dest.exists():
            sys.exit(f"{vid} already exists — archives are immutable, pick another id")

        # the id should match the build's own save format
        key = re.search(r"saveKey: *'sgt_save_(v\d+)'", src.read_text())
        if key and key.group(1) != vid:
            print(f"warning: {src.name} uses saveKey sgt_save_{key.group(1)}, "
                  f"but you are archiving it as {vid}", file=sys.stderr)

        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(src, dest)

        rows = [r for r in rows if r["id"] != vid]
        rows.append({"id": vid, "date": datetime.date.today().isoformat(),
                     "status": a.status, "note": a.note})
        write_manifest(rows)
        print(f"archived {src} -> /samegreattaste/{vid}")

    rows = read_manifest()
    (GAME / "versions").mkdir(parents=True, exist_ok=True)
    (GAME / "versions" / "index.html").write_text(render_listing(rows))
    served = live_id(rows)
    print(f"rebuilt /samegreattaste/versions (serving {served or 'an unarchived build'})")


if __name__ == "__main__":
    main()
