#!/usr/bin/env python3
"""Snapshot the live game as an immutable /samegreattaste/vNN archive.

  python3 tools/release.py                      # snapshot the current build as the next vNN
  python3 tools/release.py --note "Adds act 4"  # ...with a note for the listing
  python3 tools/release.py --id v00 --from ~/old.html --note "No sound, no transitions."

Snapshots are byte-identical copies, never rewritten, so an archived build
always behaves exactly as it did on the day it shipped. Both commands also
regenerate samegreattaste/versions/index.html from versions.tsv.
"""
import argparse, datetime, html, re, shutil, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GAME = ROOT / "samegreattaste"
LIVE = GAME / "index.html"
MANIFEST = GAME / "versions.tsv"


def read_manifest():
    rows = []
    if MANIFEST.exists():
        for line in MANIFEST.read_text().splitlines():
            if not line.strip() or line.startswith("#"):
                continue
            parts = (line.split("\t") + ["", ""])[:3]
            rows.append({"id": parts[0].strip(), "date": parts[1].strip(),
                         "note": parts[2].strip()})
    return rows


def write_manifest(rows):
    rows.sort(key=lambda r: r["id"])
    out = ["# id\tdate\tnote",
           "# Newest last. Edit notes freely; tools/release.py rebuilds the listing from this."]
    out += [f"{r['id']}\t{r['date']}\t{r['note']}" for r in rows]
    MANIFEST.write_text("\n".join(out) + "\n")


def next_id(rows):
    nums = [int(m.group(1)) for r in rows if (m := re.fullmatch(r"v(\d+)", r["id"]))]
    return f"v{(max(nums) + 1) if nums else 1:02d}"


def render_listing(rows):
    newest = rows[-1]["id"] if rows else None
    items = []
    for r in reversed(rows):
        note = html.escape(r["note"]) or "&nbsp;"
        tag = ' <span class="tag">current</span>' if r["id"] == newest else ""
        items.append(
            f'    <li>\n'
            f'      <a href="/samegreattaste/{r["id"]}">{r["id"]}{tag}</a>\n'
            f'      <p>{note}</p>\n'
            f'      <time datetime="{html.escape(r["date"])}">{html.escape(r["date"])}</time>\n'
            f'    </li>'
        )
    return f"""<!doctype html>
<!-- Generated by tools/release.py from samegreattaste/versions.tsv. Do not edit by hand. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Same Great Taste — versions</title>
<link rel="icon" href="/logo.svg" type="image/svg+xml">
<meta name="robots" content="noindex">
<meta name="theme-color" content="#f7f5f0" media="(prefers-color-scheme: light)">
<meta name="theme-color" content="#0b0e13" media="(prefers-color-scheme: dark)">
<style>
  :root{{ --page:#f7f5f0; --fg:#121821; --muted:#6b7280; --rule:#e2ded4; --accent:#499dee; }}
  @media (prefers-color-scheme:dark){{
    :root{{ --page:#0b0e13; --fg:#eceadf; --muted:#8b94a3; --rule:#20262f; }}
  }}
  *{{box-sizing:border-box;margin:0;padding:0}}
  body{{
    background:var(--page); color:var(--fg); min-height:100vh; padding:12vmin 6vmin;
    font:400 1rem/1.6 ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;
    display:flex; justify-content:center;
  }}
  main{{width:100%;max-width:34rem}}
  .mark{{width:56px;height:56px;border-radius:14px;display:block;margin-bottom:2rem}}
  h1{{font-size:1.25rem;font-weight:600;letter-spacing:-.01em}}
  .lede{{color:var(--muted);font-size:.9rem;margin:.4rem 0 2.5rem}}
  ul{{list-style:none}}
  li{{padding:1.1rem 0;border-top:1px solid var(--rule)}}
  li a{{color:var(--fg);font-weight:600;text-decoration:none;font-variant-numeric:tabular-nums}}
  li a:hover{{color:var(--accent)}}
  .tag{{
    font-size:.62rem;font-weight:600;letter-spacing:.09em;text-transform:uppercase;
    color:var(--page); background:var(--accent); padding:.16rem .42rem;
    border-radius:4px; vertical-align:.12em; margin-left:.45rem;
  }}
  li p{{color:var(--muted);font-size:.9rem;margin-top:.15rem}}
  time{{color:var(--muted);font-size:.78rem;font-variant-numeric:tabular-nums}}
  .back{{display:inline-block;margin-top:2.5rem;color:var(--muted);font-size:.85rem}}
  .back:hover{{color:var(--accent)}}
</style>
</head>
<body>
  <main>
    <img class="mark" src="/logo.svg" alt="">
    <h1>Same Great Taste — versions</h1>
    <p class="lede">Every build that has shipped, kept playable at its own address.
      <a href="/samegreattaste" style="color:inherit">/samegreattaste</a> always serves the current one.</p>
    <ul>
{chr(10).join(items)}
    </ul>
    <a class="back" href="/samegreattaste">&larr; Play the current build</a>
  </main>
</body>
</html>
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--id", help="version id to write, e.g. v00 (default: next unused)")
    ap.add_argument("--from", dest="src", help="source HTML (default: the live build)")
    ap.add_argument("--note", default="", help="one-line description for the listing")
    ap.add_argument("--relist", action="store_true",
                    help="only regenerate the listing; take no snapshot")
    a = ap.parse_args()

    rows = read_manifest()

    if not a.relist:
        src = Path(a.src).expanduser() if a.src else LIVE
        if not src.is_file():
            sys.exit(f"no such file: {src}")

        vid = a.id or next_id(rows)
        if not re.fullmatch(r"v\d+", vid):
            sys.exit(f"version id must look like v01, got {vid!r}")

        dest = GAME / vid / "index.html"
        if dest.exists():
            sys.exit(f"{vid} already exists — archives are immutable, pick another id")

        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(src, dest)

        rows = [r for r in rows if r["id"] != vid]
        rows.append({"id": vid, "date": datetime.date.today().isoformat(), "note": a.note})
        write_manifest(rows)
        print(f"archived {src} -> /samegreattaste/{vid}")

    (GAME / "versions").mkdir(parents=True, exist_ok=True)
    (GAME / "versions" / "index.html").write_text(render_listing(read_manifest()))
    print("rebuilt /samegreattaste/versions")


if __name__ == "__main__":
    main()
